// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdsC1G-WjyAaJ5ATFqu9vxZkZ-dHsLQHI',
    appId: '1:590958385902:web:d68e2acd6f39aa3c5531ff',
    messagingSenderId: '590958385902',
    projectId: 'pb-vault-401b5',
    authDomain: 'pb-vault-401b5.firebaseapp.com',
    storageBucket: 'pb-vault-401b5.firebasestorage.app',
    measurementId: 'G-XGS90Q9VXV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1yc89QaJZnPS75wcyCigcEfbeXKqdyhc',
    appId: '1:590958385902:android:70e60d9a6cafe8625531ff',
    messagingSenderId: '590958385902',
    projectId: 'pb-vault-401b5',
    storageBucket: 'pb-vault-401b5.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxY7Aw49JUHUq-EKtVVcPOGO3jFObVVco',
    appId: '1:590958385902:ios:4425ba04b8c924755531ff',
    messagingSenderId: '590958385902',
    projectId: 'pb-vault-401b5',
    storageBucket: 'pb-vault-401b5.firebasestorage.app',
    androidClientId: '590958385902-34k79pq4blnnrg05i29vtosso1nour7l.apps.googleusercontent.com',
    iosClientId: '590958385902-tq0thdmcrra8v6m8unlp47d6fae7c1gp.apps.googleusercontent.com',
    iosBundleId: 'com.abdallahelnshar.pbvault',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxY7Aw49JUHUq-EKtVVcPOGO3jFObVVco',
    appId: '1:590958385902:ios:a6a5121dc49ee5135531ff',
    messagingSenderId: '590958385902',
    projectId: 'pb-vault-401b5',
    storageBucket: 'pb-vault-401b5.firebasestorage.app',
    androidClientId: '590958385902-34k79pq4blnnrg05i29vtosso1nour7l.apps.googleusercontent.com',
    iosClientId: '590958385902-0alfg71ctpaeoq62vsf765cq9to6qe59.apps.googleusercontent.com',
    iosBundleId: 'com.example.pbVault',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdsC1G-WjyAaJ5ATFqu9vxZkZ-dHsLQHI',
    appId: '1:590958385902:web:3f3cd3df32f018165531ff',
    messagingSenderId: '590958385902',
    projectId: 'pb-vault-401b5',
    authDomain: 'pb-vault-401b5.firebaseapp.com',
    storageBucket: 'pb-vault-401b5.firebasestorage.app',
    measurementId: 'G-GXL3196CJC',
  );
}
