import 'package:pb_vault/core/utils/app_assets.dart';
import 'package:pb_vault/domain/entities/response/platform_account/platform_data.dart';
import 'package:simple_icons/simple_icons.dart';

const Map<String, PlatformData> appPlatforms = {
  ...platformMain,
  ...platformSecond,
};

const Map<String, PlatformData> platformMain = {
  'google': PlatformData(
    id: 'google',
    name: 'Google',
    website: 'https://www.google.com',
    icon: SimpleIcons.google,
    color: SimpleIconColors.google,
  ),
  'facebook': PlatformData(
    id: 'facebook',
    name: 'Facebook',
    website: 'https://www.facebook.com',
    icon: SimpleIcons.facebook,
    color: SimpleIconColors.facebook,
  ),
  'instagram': PlatformData(
    id: 'instagram',
    name: 'Instagram',
    website: 'https://www.instagram.com',
    icon: SimpleIcons.instagram,
    color: SimpleIconColors.instagram,
  ),
  'twitter': PlatformData(
    id: 'twitter',
    name: 'Twitter (X)',
    website: 'https://www.twitter.com',
    icon: SimpleIcons.x,
    color: SimpleIconColors.x,
  ),
  'github': PlatformData(
    id: 'github',
    name: 'GitHub',
    website: 'https://www.github.com',
    icon: SimpleIcons.github,
    color: SimpleIconColors.github,
  ),
  'netflix': PlatformData(
    id: 'netflix',
    name: 'Netflix',
    website: 'https://www.netflix.com',
    icon: SimpleIcons.netflix,
    color: SimpleIconColors.netflix,
  ),
  'apple': PlatformData(
    id: 'apple',
    name: 'Apple',
    website: 'https://www.apple.com',
    icon: SimpleIcons.apple,
    color: SimpleIconColors.apple,
  ),
  'spotify': PlatformData(
    id: 'spotify',
    name: 'Spotify',
    website: 'https://www.spotify.com',
    icon: SimpleIcons.spotify,
    color: SimpleIconColors.spotify,
  ),
  'youtube': PlatformData(
    id: 'youtube',
    name: 'YouTube',
    website: 'https://www.youtube.com',
    icon: SimpleIcons.youtube,
    color: SimpleIconColors.youtube,
  ),
  'tiktok': PlatformData(
    id: 'tiktok',
    name: 'TikTok',
    website: 'https://www.tiktok.com',
    icon: SimpleIcons.tiktok,
    color: SimpleIconColors.tiktok,
  ),
  'whatsapp': PlatformData(
    id: 'whatsapp',
    name: 'WhatsApp',
    website: 'https://www.whatsapp.com',
    icon: SimpleIcons.whatsapp,
    color: SimpleIconColors.whatsapp,
  ),
  'telegram': PlatformData(
    id: 'telegram',
    name: 'Telegram',
    website: 'https://telegram.org',
    icon: SimpleIcons.telegram,
    color: SimpleIconColors.telegram,
  ),
  'snapchat': PlatformData(
    id: 'snapchat',
    name: 'Snapchat',
    website: 'https://www.snapchat.com',
    icon: SimpleIcons.snapchat,
    color: SimpleIconColors.snapchat,
  ),
  'reddit': PlatformData(
    id: 'reddit',
    name: 'Reddit',
    website: 'https://www.reddit.com',
    icon: SimpleIcons.reddit,
    color: SimpleIconColors.reddit,
  ),
  'pinterest': PlatformData(
    id: 'pinterest',
    name: 'Pinterest',
    website: 'https://www.pinterest.com',
    icon: SimpleIcons.pinterest,
    color: SimpleIconColors.pinterest,
  ),
  'discord': PlatformData(
    id: 'discord',
    name: 'Discord',
    website: 'https://discord.com',
    icon: SimpleIcons.discord,
    color: SimpleIconColors.discord,
  ),
  'dropbox': PlatformData(
    id: 'dropbox',
    name: 'Dropbox',
    website: 'https://www.dropbox.com',
    icon: SimpleIcons.dropbox,
    color: SimpleIconColors.dropbox,
  ),
  'twitch': PlatformData(
    id: 'twitch',
    name: 'Twitch',
    website: 'https://www.twitch.tv',
    icon: SimpleIcons.twitch,
    color: SimpleIconColors.twitch,
  ),
  'steam': PlatformData(
    id: 'steam',
    name: 'Steam',
    website: 'https://store.steampowered.com',
    icon: SimpleIcons.steam,
    color: SimpleIconColors.steam,
  ),
  'notion': PlatformData(
    id: 'notion',
    name: 'Notion',
    website: 'https://www.notion.so',
    icon: SimpleIcons.notion,
    color: SimpleIconColors.notion,
  ),
  'trello': PlatformData(
    id: 'trello',
    name: 'Trello',
    website: 'https://trello.com',
    icon: SimpleIcons.trello,
    color: SimpleIconColors.trello,
  ),
  'asana': PlatformData(
    id: 'asana',
    name: 'Asana',
    website: 'https://asana.com',
    icon: SimpleIcons.asana,
    color: SimpleIconColors.asana,
  ),
  'zoom': PlatformData(
    id: 'zoom',
    name: 'Zoom',
    website: 'https://zoom.us',
    icon: SimpleIcons.zoom,
    color: SimpleIconColors.zoom,
  ),
  'paypal': PlatformData(
    id: 'paypal',
    name: 'PayPal',
    website: 'https://www.paypal.com',
    icon: SimpleIcons.paypal,
    color: SimpleIconColors.paypal,
  ),
  'visa': PlatformData(
    id: 'visa',
    name: 'Visa',
    website: 'https://www.visa.com',
    icon: SimpleIcons.visa,
    color: SimpleIconColors.visa,
  ),
  'mastercard': PlatformData(
    id: 'mastercard',
    name: 'Mastercard',
    website: 'https://www.mastercard.com',
    icon: SimpleIcons.mastercard,
    color: SimpleIconColors.mastercard,
  ),
  'airbnb': PlatformData(
    id: 'airbnb',
    name: 'Airbnb',
    website: 'https://www.airbnb.com',
    icon: SimpleIcons.airbnb,
    color: SimpleIconColors.airbnb,
  ),
  'uber': PlatformData(
    id: 'uber',
    name: 'Uber',
    website: 'https://www.uber.com',
    icon: SimpleIcons.uber,
    color: SimpleIconColors.uber,
  ),
  'lyft': PlatformData(
    id: 'lyft',
    name: 'Lyft',
    website: 'https://www.lyft.com',
    icon: SimpleIcons.lyft,
    color: SimpleIconColors.lyft,
  ),
  'ebay': PlatformData(
    id: 'ebay',
    name: 'Ebay',
    website: 'https://www.ebay.com',
    icon: SimpleIcons.ebay,
    color: SimpleIconColors.ebay,
  ),
  'quora': PlatformData(
    id: 'quora',
    name: 'Quora',
    website: 'https://www.quora.com',
    icon: SimpleIcons.quora,
    color: SimpleIconColors.quora,
  ),
  'medium': PlatformData(
    id: 'medium',
    name: 'Medium',
    website: 'https://medium.com',
    icon: SimpleIcons.medium,
    color: SimpleIconColors.medium,
  ),
  'wordpress': PlatformData(
    id: 'wordpress',
    name: 'WordPress',
    website: 'https://wordpress.com',
    icon: SimpleIcons.wordpress,
    color: SimpleIconColors.wordpress,
  ),
  'wix': PlatformData(
    id: 'wix',
    name: 'Wix',
    website: 'https://www.wix.com',
    icon: SimpleIcons.wix,
    color: SimpleIconColors.wix,
  ),
  'gmail': PlatformData(
    id: 'gmail',
    name: 'Gmail',
    website: 'https://mail.google.com',
    icon: SimpleIcons.gmail,
    color: SimpleIconColors.gmail,
  ),
  'protonmail': PlatformData(
    id: 'protonmail',
    name: 'Proton Mail',
    website: 'https://proton.me/mail',
    icon: SimpleIcons.protonmail,
    color: SimpleIconColors.protonmail,
  ),
  'icloud': PlatformData(
    id: 'icloud',
    name: 'iCloud',
    website: 'https://www.icloud.com',
    icon: SimpleIcons.icloud,
    color: SimpleIconColors.icloud,
  ),
  'viber': PlatformData(
    id: 'viber',
    name: 'Viber',
    website: 'https://www.viber.com',
    icon: SimpleIcons.viber,
    color: SimpleIconColors.viber,
  ),
  'signal': PlatformData(
    id: 'signal',
    name: 'Signal',
    website: 'https://signal.org',
    icon: SimpleIcons.signal,
    color: SimpleIconColors.signal,
  ),
  'line': PlatformData(
    id: 'line',
    name: 'Line',
    website: 'https://line.me',
    icon: SimpleIcons.line,
    color: SimpleIconColors.line,
  ),
  'wechat': PlatformData(
    id: 'wechat',
    name: 'WeChat',
    website: 'https://www.wechat.com',
    icon: SimpleIcons.wechat,
    color: SimpleIconColors.wechat,
  ),
  'tinder': PlatformData(
    id: 'tinder',
    name: 'Tinder',
    website: 'https://tinder.com',
    icon: SimpleIcons.tinder,
    color: SimpleIconColors.tinder,
  ),
  'badoo': PlatformData(
    id: 'badoo',
    name: 'Badoo',
    website: 'https://badoo.com',
    icon: SimpleIcons.badoo,
    color: SimpleIconColors.badoo,
  ),
  'okcupid': PlatformData(
    id: 'okcupid',
    name: 'OkCupid',
    website: 'https://www.okcupid.com',
    icon: SimpleIcons.okcupid,
    color: SimpleIconColors.okcupid,
  ),
  'deezer': PlatformData(
    id: 'deezer',
    name: 'Deezer',
    website: 'https://www.deezer.com',
    icon: SimpleIcons.deezer,
    color: SimpleIconColors.deezer,
  ),
  'tidal': PlatformData(
    id: 'tidal',
    name: 'Tidal',
    website: 'https://tidal.com',
    icon: SimpleIcons.tidal,
    color: SimpleIconColors.tidal,
  ),
  'soundcloud': PlatformData(
    id: 'soundcloud',
    name: 'SoundCloud',
    website: 'https://soundcloud.com',
    icon: SimpleIcons.soundcloud,
    color: SimpleIconColors.soundcloud,
  ),
  'pandora': PlatformData(
    id: 'pandora',
    name: 'Pandora',
    website: 'https://www.pandora.com',
    icon: SimpleIcons.pandora,
    color: SimpleIconColors.pandora,
  ),
  'hbomax': PlatformData(
    id: 'hbomax',
    name: 'HBO Max',
    website: 'https://www.hbomax.com',
    icon: SimpleIcons.hbo,
    color: SimpleIconColors.hbo,
  ),
  'paramountplus': PlatformData(
    id: 'paramountplus',
    name: 'Paramount+',
    website: 'https://www.paramountplus.com',
    icon: SimpleIcons.paramountplus,
    color: SimpleIconColors.paramountplus,
  ),
  'twitchtv': PlatformData(
    id: 'twitchtv',
    name: 'Twitch',
    website: 'https://www.twitch.tv',
    icon: SimpleIcons.twitch,
    color: SimpleIconColors.twitch,
  ),
  'epicgames': PlatformData(
    id: 'epicgames',
    name: 'Epic Games',
    website: 'https://www.epicgames.com',
    icon: SimpleIcons.epicgames,
    color: SimpleIconColors.epicgames,
  ),
  'playstation': PlatformData(
    id: 'playstation',
    name: 'PlayStation',
    website: 'https://www.playstation.com',
    icon: SimpleIcons.playstation,
    color: SimpleIconColors.playstation,
  ),
  'ubisoft': PlatformData(
    id: 'ubisoft',
    name: 'Ubisoft',
    website: 'https://www.ubisoft.com',
    icon: SimpleIcons.ubisoft,
    color: SimpleIconColors.ubisoft,
  ),
  'ea': PlatformData(
    id: 'ea',
    name: 'EA',
    website: 'https://www.ea.com',
    icon: SimpleIcons.ea,
    color: SimpleIconColors.ea,
  ),
  'battle_net': PlatformData(
    id: 'battle_net',
    name: 'Battle.net',
    website: 'https://www.battle.net',
    icon: SimpleIcons.battledotnet,
    color: SimpleIconColors.battledotnet,
  ),
  'riotgames': PlatformData(
    id: 'riotgames',
    name: 'Riot Games',
    website: 'https://www.riotgames.com',
    icon: SimpleIcons.riotgames,
    color: SimpleIconColors.riotgames,
  ),
  'roblox': PlatformData(
    id: 'roblox',
    name: 'Roblox',
    website: 'https://www.roblox.com',
    icon: SimpleIcons.roblox,
    color: SimpleIconColors.roblox,
  ),
  'unity': PlatformData(
    id: 'unity',
    name: 'Unity',
    website: 'https://unity.com',
    icon: SimpleIcons.unity,
    color: SimpleIconColors.unity,
  ),
  'unrealengine': PlatformData(
    id: 'unrealengine',
    name: 'Unreal Engine',
    website: 'https://www.unrealengine.com',
    icon: SimpleIcons.unrealengine,
    color: SimpleIconColors.unrealengine,
  ),
  'evernote': PlatformData(
    id: 'evernote',
    name: 'Evernote',
    website: 'https://evernote.com',
    icon: SimpleIcons.evernote,
    color: SimpleIconColors.evernote,
  ),
  'todoist': PlatformData(
    id: 'todoist',
    name: 'Todoist',
    website: 'https://todoist.com',
    icon: SimpleIcons.todoist,
    color: SimpleIconColors.todoist,
  ),
  'ticktick': PlatformData(
    id: 'ticktick',
    name: 'TickTick',
    website: 'https://ticktick.com',
    icon: SimpleIcons.ticktick,
    color: SimpleIconColors.ticktick,
  ),
  'instapaper': PlatformData(
    id: 'instapaper',
    name: 'Instapaper',
    website: 'https://www.instapaper.com',
    icon: SimpleIcons.instapaper,
    color: SimpleIconColors.instapaper,
  ),
  'jira': PlatformData(
    id: 'jira',
    name: 'Jira',
    website: 'https://www.atlassian.com/software/jira',
    icon: SimpleIcons.jira,
    color: SimpleIconColors.jira,
  ),
  'confluence': PlatformData(
    id: 'confluence',
    name: 'Confluence',
    website: 'https://www.atlassian.com/software/confluence',
    icon: SimpleIcons.confluence,
    color: SimpleIconColors.confluence,
  ),
  'bitbucket': PlatformData(
    id: 'bitbucket',
    name: 'Bitbucket',
    website: 'https://bitbucket.org',
    icon: SimpleIcons.bitbucket,
    color: SimpleIconColors.bitbucket,
  ),
  'gitlab': PlatformData(
    id: 'gitlab',
    name: 'GitLab',
    website: 'https://about.gitlab.com',
    icon: SimpleIcons.gitlab,
    color: SimpleIconColors.gitlab,
  ),
  'digitalocean': PlatformData(
    id: 'digitalocean',
    name: 'DigitalOcean',
    website: 'https://www.digitalocean.com',
    icon: SimpleIcons.digitalocean,
    color: SimpleIconColors.digitalocean,
  ),
  'cloudflare': PlatformData(
    id: 'cloudflare',
    name: 'Cloudflare',
    website: 'https://www.cloudflare.com',
    icon: SimpleIcons.cloudflare,
    color: SimpleIconColors.cloudflare,
  ),
  'godaddy': PlatformData(
    id: 'godaddy',
    name: 'GoDaddy',
    website: 'https://www.godaddy.com',
    icon: SimpleIcons.godaddy,
    color: SimpleIconColors.godaddy,
  ),
  'namecheap': PlatformData(
    id: 'namecheap',
    name: 'Namecheap',
    website: 'https://www.namecheap.com',
    icon: SimpleIcons.namecheap,
    color: SimpleIconColors.namecheap,
  ),
  'shopify': PlatformData(
    id: 'shopify',
    name: 'Shopify',
    website: 'https://www.shopify.com',
    icon: SimpleIcons.shopify,
    color: SimpleIconColors.shopify,
  ),
  'woocommerce': PlatformData(
    id: 'woocommerce',
    name: 'WooCommerce',
    website: 'https://woocommerce.com',
    icon: SimpleIcons.woocommerce,
    color: SimpleIconColors.woocommerce,
  ),
  'stripe': PlatformData(
    id: 'stripe',
    name: 'Stripe',
    website: 'https://stripe.com',
    icon: SimpleIcons.stripe,
    color: SimpleIconColors.stripe,
  ),
  'square': PlatformData(
    id: 'square',
    name: 'Square',
    website: 'https://squareup.com',
    icon: SimpleIcons.square,
    color: SimpleIconColors.square,
  ),
  'revolut': PlatformData(
    id: 'revolut',
    name: 'Revolut',
    website: 'https://www.revolut.com',
    icon: SimpleIcons.revolut,
    color: SimpleIconColors.revolut,
  ),
  'monzo': PlatformData(
    id: 'monzo',
    name: 'Monzo',
    website: 'https://monzo.com',
    icon: SimpleIcons.monzo,
    color: SimpleIconColors.monzo,
  ),
  'wise': PlatformData(
    id: 'wise',
    name: 'Wise',
    website: 'https://wise.com',
    icon: SimpleIcons.wise,
    color: SimpleIconColors.wise,
  ),
  'payoneer': PlatformData(
    id: 'payoneer',
    name: 'Payoneer',
    website: 'https://www.payoneer.com',
    icon: SimpleIcons.payoneer,
    color: SimpleIconColors.payoneer,
  ),
  'coinbase': PlatformData(
    id: 'coinbase',
    name: 'Coinbase',
    website: 'https://www.coinbase.com',
    icon: SimpleIcons.coinbase,
    color: SimpleIconColors.coinbase,
  ),
  'binance': PlatformData(
    id: 'binance',
    name: 'Binance',
    website: 'https://www.binance.com',
    icon: SimpleIcons.binance,
    color: SimpleIconColors.binance,
  ),
  'coursera': PlatformData(
    id: 'coursera',
    name: 'Coursera',
    website: 'https://www.coursera.org',
    icon: SimpleIcons.coursera,
    color: SimpleIconColors.coursera,
  ),
  'udemy': PlatformData(
    id: 'udemy',
    name: 'Udemy',
    website: 'https://www.udemy.com',
    icon: SimpleIcons.udemy,
    color: SimpleIconColors.udemy,
  ),
  'edx': PlatformData(
    id: 'edx',
    name: 'edX',
    website: 'https://www.edx.org',
    icon: SimpleIcons.edx,
    color: SimpleIconColors.edx,
  ),
  'khanacademy': PlatformData(
    id: 'khanacademy',
    name: 'Khan Academy',
    website: 'https://www.khanacademy.org',
    icon: SimpleIcons.khanacademy,
    color: SimpleIconColors.khanacademy,
  ),
  'skillshare': PlatformData(
    id: 'skillshare',
    name: 'Skillshare',
    website: 'https://www.skillshare.com',
    icon: SimpleIcons.skillshare,
    color: SimpleIconColors.skillshare,
  ),
  'duolingo': PlatformData(
    id: 'duolingo',
    name: 'Duolingo',
    website: 'https://www.duolingo.com',
    icon: SimpleIcons.duolingo,
    color: SimpleIconColors.duolingo,
  ),
  'grammarly': PlatformData(
    id: 'grammarly',
    name: 'Grammarly',
    website: 'https://www.grammarly.com',
    icon: SimpleIcons.grammarly,
    color: SimpleIconColors.grammarly,
  ),
  'overleaf': PlatformData(
    id: 'overleaf',
    name: 'Overleaf',
    website: 'https://www.overleaf.com',
    icon: SimpleIcons.overleaf,
    color: SimpleIconColors.overleaf,
  ),
  'latex': PlatformData(
    id: 'latex',
    name: 'LaTeX',
    website: 'https://www.latex-project.org',
    icon: SimpleIcons.latex,
    color: SimpleIconColors.latex,
  ),
  'stackoverflow': PlatformData(
    id: 'stackoverflow',
    name: 'Stack Overflow',
    website: 'https://stackoverflow.com',
    icon: SimpleIcons.stackoverflow,
    color: SimpleIconColors.stackoverflow,
  ),
  'reddit_social': PlatformData(
    id: 'reddit_social',
    name: 'Reddit',
    website: 'https://www.reddit.com',
    icon: SimpleIcons.reddit,
    color: SimpleIconColors.reddit,
  ),
};

const Map<String, PlatformData> platformSecond = {
  'linkedin': PlatformData(
    id: 'linkedin',
    name: 'LinkedIn',
    website: 'https://www.linkedin.com',
    iconPath: AppAssets.linkedinIcon,
  ),
  'amazon': PlatformData(
    id: 'amazon',
    name: 'Amazon',
    website: 'https://www.amazon.com',
    iconPath: AppAssets.amazonIcon,
  ),
  'microsoft': PlatformData(
    id: 'microsoft',
    name: 'Microsoft',
    website: 'https://www.microsoft.com',
    iconPath: AppAssets.microsoftIcon,
  ),
  'adobe': PlatformData(
    id: 'adobe',
    name: 'Adobe',
    website: 'https://www.adobe.com',
    iconPath: AppAssets.adobeIcon,
  ),
  'canva': PlatformData(
    id: 'canva',
    name: 'Canva',
    website: 'https://www.canva.com',
    iconPath: AppAssets.canvaIcon,
  ),
  'skype': PlatformData(
    id: 'skype',
    name: 'Skype',
    website: 'https://www.skype.com',
    iconPath: AppAssets.skypeIcon,
  ),
  'minecraft': PlatformData(
    id: 'minecraft',
    name: 'Minecraft',
    website: 'https://www.minecraft.net',
    iconPath: AppAssets.minecraftIcon,
  ),
  'hulu': PlatformData(
    id: 'hulu',
    name: 'Hulu',
    website: 'https://www.hulu.com',
    iconPath: AppAssets.huluIcon,
  ),
  'disneyplus': PlatformData(
    id: 'disneyplus',
    name: 'Disney+',
    website: 'https://www.disneyplus.com',
    iconPath: AppAssets.disneyPlusIcon,
  ),
  'xbox': PlatformData(
    id: 'xbox',
    name: 'Xbox',
    website: 'https://www.xbox.com',
    iconPath: AppAssets.xboxIcon,
  ),
};
